# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Aumento de memoria para el proceso general de Gradle
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m

# Memoria exclusiva para el Daemon de Kotlin (evita el error code: 0)
kotlin.daemon.jvmargs=-Xmx2048m

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

android.useAndroidX=true
android.enableJetifier=true